### ISSUE TITLE
Necessity of source and destination region validation

### ISSUE THREAD

**Issue by castodius** [alma-cdk/cross-region-parameter#4]
I was curious if the [region validation](https://github.com/alma-cdk/cross-region-parameter/blob/a585bae0ed3b9eaef643f809e024f192481d9e99/src/parameter.ts#L99) is necessary.

I find myself in a situation where resources from different stacks will write their ARNs to a main region. This stack is also present in the main region. This has caused me to add if-else logic for setting up a CrossRegionParameter or a StringParameter depending on the region. It would be much nicer to just rely on CrossRegionParameter for all regions.

**Comment by aripalo** [comment]
Hi! I do understand your use case but the original intention of this construct was to only enforce the use of this to truly cross-region parameters, since using the "native" StringParameter is always more reliable and faster than using this construct that is based on a Lambda-backed CloudFormation custom resource.

I'm hesitant to remove the region validation just for one use case, so I may consider it if there's more requests for that in the future.

In your case, I might actually create a "wrapper construct" that has that if-else logic in one place (and depending on the condition would utilize either this CrossRegionParameter or native StringParameter). Then it would be easier just to use that wrapper construct through your codebase without having to code the if-else logic all over the place.

**Comment by aripalo** [comment]
After some more consideration, I'm closing this as "wont fix". 

I know, this might be dissapointing 😞 but I still feel that for majority of uses cases this decision is better. And again, you could circumvent this by wrapping this into a construct yourself with the necessary if-else logic.

At first I thought that we might take inspiration from the [`acm.DnsValidatedCertificate`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager-readme.html#cross-region-certificates) which allows you to deploy the certificate to any region; But in case of the `acm.DnsValidatedCertificate` it is very much ok to deploy to same region conceptually. For `CrossRegionParameter` it would be a bit weird conceptually.

Also as stated previously, I really want to avoid leading people into using this construct (with CFN custom resource implementation) for same region parameters in most cases.
